#!/bin/bash

tagver="00"
tilepath=$1
#tagset="/data-sde/data/l7g/tagset.fa/tagset.fa.gz"
tagset="/data-sdd/data/l7g/tagset.fa/tagset.fa.gz"

if [ "$tilepath" == "" ] ; then
  echo "provide tilepath"
  exit 1
fi

echo '>{"type":"tagset","path":"'$tilepath'","field":{0:"path",1:"step",2:"startTag"}}'
echo "$tilepath,0000,"

tilestep=1

while read line ; do
  hstep=`printf '%04x' $tilestep`

  echo "$tilepath,$hstep,$line"

  let tilestep="$tilestep + 1"
done < <( samtools faidx $tagset $tilepath.$tagver | egrep -v '^>' | tr -d '\n' | fold -w 24 ; echo )


