#!/usr/bin/python
#
# save a numpy array (used for saving the names of the
# datasets as a numpy array).
#

import sys
import numpy as np

ofile="tmp/list.npy"

if len(sys.argv)<2:
  print "provide file"
  sys.exit(0)

if len(sys.argv)>2:
  ofile = sys.argv[2]

with open(sys.argv[1]) as fp:
  lines = fp.readlines()

a = np.array([], dtype=str)
for x in lines:
  a = np.append(a, x.strip())

np.save(ofile, a)
