#!/bin/bash

set -a

DEBUG=0
export VERBOSE=1

function _q {
  echo $1
  exit 1
}

gffInitial="$1"

if [ "$gffInitial" == "" ] ; then
  echo "provide file"
  exit 1
fi

trap "ERROR: $gffInitial $path ; exit" ERR

export ref="$2"
export reffa="$3"
export afn="$4"
export tagset="$5"
export l7g="$6"
export pasta="$7"
export refstream="$8"

args=( "$@" )
export chroms="${args[@]:8}"

export aidx="${afn%.*}.fwi"

echo "individual variable listings"
echo "gff $gffInitial"
echo "ref $ref"
echo "reffa $reffa"
echo "afn $afn"
echo "tagset $tagset"
echo "pasta $pasta"
echo "refstream $refstream"
echo "l7g $l7g"
echo "chroms ${chroms[@]}"

ifnInitial=`basename $gffInitial`
stripped_name=`basename $ifnInitial .gff.gz`
export gff=$gffInitial

for chrom in $chroms; do

  echo $stripped_name processing $chrom

  odir="stage/$stripped_name"
  mkdir -p $odir

  while read line
  do

    path=`echo "$line" | cut -f1 | cut -f3 -d':'`

    #echo "path $path"
    
    byte_start=`echo "$line" | cut -f3`
    byte_len=`echo "$line" | cut -f2`

    #echo "byte_start $byte_start"
    #echo "bye_len $byte_len"

    export ref_start0=`$l7g assembly-range $afn $path | tail -n1 | cut -f2`
    export ref_end0=`$l7g assembly-range $afn $path | tail -n1 | cut -f3`

    #echo "ref_start0 $ref_start0"
    #echo "ref_end0 $ref_end0"

    export ref_start1=`expr "$ref_start0" + 1`
    export ref_end1=`expr "$ref_end0" + 1`

    #echo "ref_start1 $ref_start1"
    #echo "ref_end1 $ref_end1"

    export realstart1=`tabix $gff $chrom:$ref_start1-$ref_end0 | head -n1 | cut -f4`
    export realend1=`tabix $gff $chrom:$ref_start1-$ref_end0 | tail -n1 | cut -f5`

    if [ "$realstart1" == "" ] ; then
      realstart1=$ref_start1
    fi

    if [ "$realend1" == "" ] ; then
      realend1=$ref_end0
    fi

    if [[ "$VERBOSE" -eq 1 ]] ; then
      echo "cp0 ($realend1 $realstart1)"
      echo "tabix $gff $chrom:$ref_start1-$ref_end0 | tail -n1 | cut -f5"
    fi

    export realdn=`expr "$realend1" - "$realstart1"`
    export dn=`expr "$ref_end0" - "$ref_start0"`

    export window_start1="$realstart1"
    if [ "$realstart1" -ge "$ref_start1" ]
    then
      export realstart1="$ref_start1"
      export window_start1="$ref_start1"
    fi

    export window_start0=`expr "$window_start1" - 1` || true

    export window_end1="$realend1"
    if [ "$ref_end1" -ge "$realend1" ]
    then
      export realend1=$ref_end1
      export window_end1="$ref_end1"
    fi

    export window_end0=`expr "$window_end1" - 1` || true

    if [[ "$VERBOSE" -eq 1 ]] ; then
      echo "$pasta -action gff-rotini -start $window_start0 \
        -refstream <( $refstream $reffa $chrom:$window_start1-$window_end1 ) \
        -i <( cat <( echo -e '\n\n\n' ) <( tabix $gff $chrom:$window_start1-$window_end1 ) ) | \
        $pasta -action filter-rotini -start $ref_start0 -n $dn > $odir/$path.pa"
      echo -e "\n\n\n\n"
    fi

    $pasta -action gff-rotini -start $window_start0 -chrom $chrom \
      -refstream <( $refstream $reffa $chrom:$window_start1-$window_end1 ) \
      -i <( cat <( echo -e '\n\n\n' ) <( tabix $gff $chrom:$window_start1-$window_end1 ) ) | \
      $pasta -action filter-rotini -start $ref_start0 -n $dn > $odir/$path.pa

    if [[ "$VERBOSE" -eq 1 ]] ; then
      echo "refstream $reffa $chrom:$window_start1-$window_end1"
      echo "$pasta -action rotini-fastj -start $ref_start0 -tilepath $path -chrom $chrom -build $ref \
        -i $odir/$path.pa \
        -assembly <( l7g assembly $afn $path ) \
        -tag <( samtools faidx $tagset $path.00 | egrep -v '^>' | tr -d '\n' | fold -w 24 ) > $odir/$path.fj "
      echo -e "\n\n\n"
    fi

    $pasta -action rotini-fastj -start $ref_start0 -tilepath $path -chrom $chrom -build $ref \
      -i $odir/$path.pa \
      -assembly <( $l7g assembly $afn $path ) \
      -tag <( cat <( samtools faidx $tagset $path.00 | egrep -v '^>' | tr -d '\n' | fold -w 24 ) <( echo "" ) ) > $odir/$path.fj

    rm $odir/$path.pa
    bgzip -f $odir/$path.fj
    bgzip -r $odir/$path.fj.gz

  done < <( egrep '^'$ref':'$chrom':' $aidx )

done # chrom
