#!/usr/bin/python
#

import sys

if len(sys.argv) < 2:
  print "provide QUAL threshold"
  sys.exit(1)


quality_threshold = float(sys.argv[1])

for line in sys.stdin:
  line = line.strip()

  if len(line)==0:
    print ""
    continue
  if line[0]=='#':
    print line
    continue

  fields = line.split("\t")
  if len(fields)<10: continue

  keys = fields[8].split(":")
  vals = fields[9].split(":")

  gq=100.0
  for k,kn in enumerate(keys):
    if kn=="GQ":
      gq=float(vals[k])
      break
  if quality_threshold <= gq:
    print line


