#!/bin/bash
#
# a thin wrapper around 'samtools faidx' to help get a stream
# out of a FASTA file easily.
#
# Assumes `hg19.fa` located in $HOME/data/ref/hg19.fa unless
# specified on the command line.
#
# example usage:
#
#     refstream chrM
#
#     refstream /path/to/ref/data/hg19.fa chr3:500-1000
#
#     refstream /path/to/ref/data/hg19.fa chrM:30+10
#

fn=$1
r=$2

if [ "$r" == "" ]
then
  r=$fn
  fn="$HOME/data/ref/hg19.fa"
fi

if [[ "$r" =~ \+ ]]
then
  s=`echo "$r" | cut -f1 -d'+' | cut -f2 -d':'`
  e=`echo "$r" | cut -f2 -d'+'`
  z=`expr "$s" + "$e" - 1`
  r=`echo "$r" | cut -f1 -d'+'`'-'$z
fi

samtools faidx $fn $r | egrep -v '^>' | tr '[:upper:]' '[:lower:]' | tr 'm' 'n'
