#!/usr/bin/python

import argparse
import gzip


def filter_gvcf():

    # setting up inputs
    parser = argparse.ArgumentParser(prog="filter-gvcf", description="Filter a \
        gVCF with a user-set quality threshold.")
    parser.add_argument("-k", "--keepGQdot", help="Keeps the variant when GQ \
        is '.'", action="store_true")
    parser.add_argument("quality_threshold", metavar="QUALITY", help="Quality \
        threshold", type=float)
    parser.add_argument("gvcf", metavar="GVCF", help="Input gVCF to filter")

    args = parser.parse_args()
    keepGQdot = args.keepGQdot
    quality_threshold = args.quality_threshold
    gvcf = args.gvcf

    # open with gzip if GVCF is gzipped
    g = gzip.open(gvcf) if gvcf.endswith(".gz") else open(gvcf)

    for line in g:
        line = line.strip()

        # retain header and info lines
        if len(line) == 0:
            print ""
            continue
        if line[0] == '#':
            print line
            continue

        fields = line.split('\t')

        if len(fields) < 10:
            continue

        # create dictionary
        keys = fields[8].split(":")
        vals = fields[9].split(":")
        d = dict(zip(keys, vals))

        # filter quality scores below the threshold
        gq = 100.0
        if "GQ" in d:
            gq = d['GQ']
            # checking if keepGQdot flag is on
            if gq == "." and keepGQdot:
                print line
            elif gq.isdigit():
                gq = float(gq)
                if quality_threshold <= gq:
                    print line
        else:
            print line

if __name__ == '__main__':
    filter_gvcf()
