#!/bin/bash

export GOMAXPROCS=1

set -eo pipefail

#ls /data-sde/data/pgp-gff/*.gff.gz | xargs -n1 -P 15 -I{} time echo {}
ls /data-sde/data/cgi-1kg-69/*.gff.gz | xargs -n1 -P 15 -I{} time ./convert-gff-1kg-cgi-69-single {}
