#!/usr/bin/python

import sys
import argparse


def filter_gvcf():

    # setting up inputs
    parser = argparse.ArgumentParser()
    parser.add_argument("--keepGQdot" help="Keeps the variant when GQ is '.'"
                        action="store_true")
    parser.add_argument("quality_threshold" help="Quality threshold"
                        type=float(2))
    parser.add_argument("input_gvcf" help="Input gVCF to filter")
    args = parser.parse_args()
    keepGQdot = args.keepGQdot
    quality_threshold = args.quality_threshold
    input_gvcf = args.input_gvcf

    if len(sys.argv) < 2:
        print "provide QUAL threshold"
        sys.exit(1)

    # quality_threshold = float(sys.argv[1])

    for line in sys.stdin:
        line = line.strip()

    if len(line) == 0:
        print ""
        continue
    if line[0] == '#':
        print line
        continue

    fields = line.split("\t")
    if len(fields) < 10:
        continue

    keys = fields[8].split(":")
    vals = fields[9].split(":")

    gq = 100.0
    for k, kn in enumerate(keys):
        if kn == "GQ":
            if keepGQdot:
                gq = "."
                # do something here
                break
            else:
                gq = float(vals[k])
                break
    if quality_threshold <= gq:
        print line

if __name__ == '__main__':
    filter_gvcf()


# convert to using a real dictionary, potentially fix loop
# switch statement???
# convert all args to argparse
