#!/bin/bash

set -a

DEBUG=0
export MAKE_NEW_DIR=1

function _q {
  echo $1
  exit 1
}

gffDir="$1"
gffPrefix="$2"

if [ "$gffDir" == "" ] ; then
  echo "provide inital directory"
  exit 1
fi

trap "ERROR: $gffDir $path ; exit" ERR

export ref1="$3"
export reffa1="$4"
export afn1="$5"
export aidx1="$6"

export refM="$7"
export reffaM="$8"
export afnM="$9"
export aidxM="${10}"
export seqidM="${11}"

export tagdir="${12}"
export l7g="${13}"
export pasta="${14}"
export refstream="${15}"
export tile_assembly="${16}"

export LD_LIBRARY_PATH='/usr/local/bin'

echo "individual variable listings"
echo "dir $gffDir"
echo "ref $ref1"
echo "reffa $reffa1"
echo "afn $afn1"
echo "aidx $aidx1"
echo "refM $refM"
echo "reffaM $reffaM"
echo "afnM  $afnM"
echo "aidxM $aidxM"
echo "seqidM $seqidM"
echo "tagdir $tagdir"
echo "pasta $pasta"
echo "refstream $refstream"
echo "l7g $l7g"
echo "tile_assembly $tile_assembly"

mkdir -p 'indexed'

#ifnInitial=`basename $gffInitial`
#export gff=$gffInitial

#ifn=`basename $gff`
#extensionfull=${ifn#*.}
#extensionfull='.'$extensionfull
#stripped_name=`basename $ifn $extensionfull`

#huid=`echo "$stripped_name" | cut -f1 -d'-'`
#dnaid=`echo "$stripped_name" | cut -f2- -d'-'`

for chrom in chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY chrM ; do

   gffInitial=$gffDir'/filtered_'$gffPrefix.raw_variants.$chrom.gvcf.gz
   echo "$gffInitial"

   ifnInitial=`basename $gffInitial`
   echo "$ifnInitial"
 
   stripped_name=`basename $ifnInitial .gvcf.gz`

   echo "$stripped_name"

   if [[ "$MAKE_NEW_DIR" != 1 ]] ; then
     tabix -f $gffInitial
     gff=$gffInitial
   else
#     mkdir -p cleaned
#     gunzip --to-stdout $gffInitial | bgzip > 'indexed/'$stripped_name'.gvcf.gz'
     cp -f $gffInitial 'indexed/'$stripped_name'.gvcf.gz'
     gff='indexed/'$stripped_name'.gvcf.gz'
     tabix -f $gff
   fi

   echo "$gff"

# Change reference if alternative ref for ChrM
  if [ "$chrom" == "chrM" ] ; then
    echo "Using $refM ref for $chrom"
    export ref=$refM
    export reffa=$reffaM
    export afn=$afnM
    export aidx=$aidxM
    export refchrom=$seqidM
  else
    export ref=$ref1
    export reffa=$reffa1
    export afn=$afn1
    export aidx=$aidx1
    export refchrom=$chrom
  fi

  echo $stripped_name processing $chrom

  odir="stage/$gffPrefix"
  mkdir -p $odir

  while read line
  do

    path=`echo "$line" | cut -f1 | cut -f3 -d':'`

    echo "path $path"

    byte_start=`echo "$line" | cut -f3`
    byte_len=`echo "$line" | cut -f2`

    echo "  byte_start $byte_start"
    echo "  byte_len $byte_len"

    ## Due to technical limitations, we can't convert from gVCF in the middle
    ## of a gVCF line.
    ## If the first gVCF line starts after the start of the tile path, use the tilepath start
    ##   as the beginning point.
    ## If the beginning of the tile path starts in the middle of the gVCF line, start at
    ## the beginning of the gVCF line.
    ##
    ## The ending gVCF line has similar complications.
    ## If the last gVCF line ends before end of the tilepath, use the end of the tilepath
    ## If the end of the tilepath falls in the middle of the last gVCF line, use the ending
    ##   of the gVCF line as the end.
    ## Care has to be taken as the gVCF can have an 'END' filed which has the end of the
    ##   block in question.
    ## If the 'END' field isn't present, but the reference sequence is greater than 1, the
    ##   length of the reference sequence is taken as the length of the block.
    ##
    ## "window_start" is where the final start of the window for filtering the gVCF is stored
    ## "ref_dn" is the window length
    ## "ref_start0" is the start of the tilepath
    ## "dn" is the length of the tilepath
    ##
    ## The larger window is converted from gVCF to PASTA and is then filtered down
    ## to the proper tilepath length.
    ##
    ##  [window_start ....  +ref_dn)
    ##   [ref_start0  .... +dn)
    ##

    export ref_start0=`$l7g assembly-range $afn $path | tail -n1 | cut -f2`
    export ref_end0_noninc=`$l7g assembly-range $afn $path | tail -n1 | cut -f3`
    export ref_end1_inc="$ref_end0_noninc"

    echo ">>>" "$l7g assembly-range $afn $path | tail -n1 | cut -f2"
    echo ">>>" "$l7g assembly-range $afn $path | tail -n1 | cut -f3"

    echo "  ref_start0 $ref_start0"
    echo "  ref_end0_noninc $ref_end0_noninc"
    echo "  ref_end1_inc $ref_end1_inc"

    export ref_start1=`expr "$ref_start0" + 1`
    export ref_end1_noninc=`expr "$ref_end0_noninc" + 1`

    echo "  ref_start1 $ref_start1"
    echo "  ref_end1 $ref_end1_noninc"

    export realstart1=`tabix $gff $chrom:$ref_start1-$ref_end1_inc | head -n1 | cut -f2`
    export realend1_inc=`tabix $gff $chrom:$ref_start1-$ref_end1_inc | tail -n1 | cut -f2`

    alt_end1_inc=`tabix $gff $chrom:$ref_start1-$ref_end1_inc | grep END | tail -n1 | cut -f8 | cut -f2 -d'='`
    if [[ "$alt_end1_inc" != "" ]] && [[ "$alt_end1_inc" -ge "$realend1_inc" ]] ; then
      realend1_inc="$alt_end1_inc"
    fi

    ## take the maximum of the 'END' field or the length of the reference sequence
    ## in the 'REF' column.
    ##
    alt_len=`tabix $gff $chrom:$ref_start1-$ref_end1_inc | tail -n1 | cut -f4 | tr -d '\n' | wc -c`
    alt_start1=`tabix $gff $chrom:$ref_start1-$ref_end1_inc | tail -n1 | cut -f2 | tr -d '\n' `
    alt_end1_inc=`expr $alt_start1 + $alt_len - 1`

    if [[ "$alt_end1_inc" != "" ]] && [[ "$alt_end1_inc" -ge "$realend1_inc" ]] ; then
      realend1_inc="$alt_end1_inc"
    fi


    if [ "$realstart1" == "" ] ; then
      realstart1=$ref_start1
    fi

    if [ "$realend1_inc" == "" ] ; then
      realend1_inc=$ref_end0_noninc
    fi

    echo "cp1"
    echo "cp1 $path" 1>&2
    echo "  realend1_inc $realend1_inc"
    echo "  realstart1 $realstart1"
    echo "  ref_end0_noninc $ref_end0_noninc"
    echo "  ref_start0 $ref_start0"
    echo "  alt_end1_inc $alt_end1_inc"

    export realdn=`expr "$realend1_inc" - "$realstart1" "+" "1"`
    export dn=`expr "$ref_end0_noninc" - "$ref_start0"`

    export window_start1="$realstart1"
    if [ "$realstart1" -ge "$ref_start1" ]
    then
      export realstart1="$ref_start1"
      export window_start1="$ref_start1"
    fi

    echo "  window_start1 $window_start1"

    export window_start0=`expr "$window_start1" - 1` || true

    echo "cp2"
    echo "cp2 $path" 1>&2

    export window_end1_inc="$realend1_inc"
    #if [ "$ref_end1" -ge "$realend1" ]
    #then
    #  export realend1=$ref_end1
    #  export window_end1="$ref_end1"
    #fi

    ## if the window length is smaller that the size of the
    ## reference tilepath length, pad out the reference stream.
    ## We'll filter extra sequence outside of the window
    ## later.
    export ref_dn=`expr "$window_end1_inc" "-" "$window_start1" "+" 1 `
    if [[ "$ref_dn" -lt "$dn" ]] ; then

      ## make sure to consider the reference before the start of the tilepath
      ## (if any)
      ##
      ref_dn=`expr "$ref_start0" - "$window_start0" "+" "$dn" "+" "1"`
      #ref_dn=`expr "$dn" "+" "1" `

    fi

    if [[ "$window_start1" -ge "$window_end1_inc" ]] ; then
      echo "SKIPPING EMPTY TILEPATH $path (window: $window_start1-$window_end1_inc)"
      continue
    fi

    ## I'm getting segfaults from what I think are truncated streams.  I think the issue
    ## is tabix for some reason prematurely terminating the stream.
    ## To try and mitigate this, write to a temporary file then delete afterwards
    ##
    tdir=`mktemp -d`

    echo "## TDIR: $tdir"
    echo "## REF_DN: $ref_dn (dn $dn)"

    #$refstream $reffa $refchrom:$window_start1-$window_end1 > $tdir/$path.ref
    $refstream $reffa "$refchrom:$window_start1+$ref_dn" > $tdir/$path.ref
    cat <( echo -e '\n\n\n' ) <( tabix $gff $chrom:$window_start1-$window_end1_inc ) > $tdir/$path.gvcf

    echo "$pasta -action gvcf-rotini -start $window_start0 -chrom $chrom \
      -refstream $tdir/$path.ref \
      -i $tdir/$path.gvcf | \
      $pasta -action filter-rotini -start $ref_start0 -n $dn > $odir/$path.pa"

    $pasta -action gvcf-rotini -start $window_start0 -chrom $chrom \
      -full-sequence \
      -refstream $tdir/$path.ref \
      -i $tdir/$path.gvcf | \
      $pasta -action filter-rotini -start $ref_start0 -n $dn > $odir/$path.pa

    ## clean up gvcf and ref temporary files
    ##
    rm -rf $tdir

    echo "cp3"
    echo "cp3 $path" 1>&2

    echo "$pasta -action rotini-fastj -start $ref_start0 -tilepath $path -chrom $chrom -build $ref \
      -i $odir/$path.pa \
      -assembly <( $tile_assembly tilepath $afn $path ) \
      -tag <( cat <( samtools faidx $tagdir $path.00 | egrep -v '^>' | tr -d '\n' | fold -w 24 ) <(echo ) ) > $odir/$path.fj"

     $pasta -action rotini-fastj -start $ref_start0 -tilepath $path -chrom $chrom -build $ref \
      -i $odir/$path.pa \
      -assembly <( $tile_assembly tilepath $afn $path ) \
      -tag <( cat <( samtools faidx $tagdir $path.00 | egrep -v '^>' | tr -d '\n' | fold -w 24 ) <( echo )  ) > $odir/$path.fj

      #-assembly <( $l7g assembly $afn $path ) \

    echo "cp4"
    echo "cp4 $path" 1>&2

    #rm $odir/$path.pa
    bgzip -f $odir/$path.fj
    bgzip -r $odir/$path.fj.gz

  done < <( egrep '^'$ref':'$refchrom':' $aidx )

done # chrom
